language: php

php:
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit
