language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
    - php: 5.5

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit
  - bin/pgca analyze --printer=console --serializer=console --composer=simple --from HEAD~1..HEAD
