language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
    - php: 5.5
    - php: hhvm

before_script:
  - travis_retry composer self-update --no-progress -n
  - travis_retry composer install -n --prefer-source

script:
  - phpunit
  - bin/pgca analyze --printer=console --serializer=console --composer=simple --tolerance=20 --revision HEAD~10..HEAD
