language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
    - php: 5.5
    - php: hhvm

before_script:
  - travis_retry composer self-update --no-progress -n
  - travis_retry composer install -n --prefer-source

script:
  # Find php syntax errors
  - php -l src
  - php -l tests

  # Run unit tests
  - phpunit

  # Check for coding standard violations
  - vendor/bin/phpcs --standard=PSR2 src tests

  # Check for code design violations
  - vendor/bin/phpmd src,tests text cleancode,codesize,controversial,design,naming,unusedcode

  # Print statistics about commit messages
  - bin/pgca analyze --printer=console --serializer=console --composer=simple --tolerance=15 --revision HEAD~10..HEAD
  - bin/pgca analyze --composer=blame --revision HEAD~40..HEAD --tolerance=100

notifications:
  email:
    on_success: never