language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
    - php: 5.5
    - php: hhvm

before_script:
  - travis_retry composer self-update --no-progress -n
  - travis_retry composer install -n --prefer-source

script:
  - php -l src
  - php -l tests
  - phpunit
  - vendor/bin/phpcs --standard=PSR2 src
  - vendor/bin/phpcs --standard=PSR2 tests
  - vendor/bin/phpmd src text cleancode,codesize,controversial,design,naming,unusedcode
  - vendor/bin/phpmd tests text cleancode,codesize,controversial,design,naming,unusedcode
  - bin/pgca analyze --printer=console --serializer=console --composer=simple --tolerance=14 --revision HEAD~10..HEAD

notifications:
  email:
    on_success: never