provider:
  name: fileSystemProvider
  path: .
  filters:
    - name: isNotMergeCommit


analyzers:
  message:
    rules:
      - name: message.hasSummaryAndDescription
      - name: message.startsWithCapitalLetter
      - name: message.oneBlankLineAfterSummary
      - name: message.summaryFiftyOrLessChars
      - name: message.isTooShort
      - name: message.hasTrailingWhitespace
      - name: message.hasTrailingNewline
      - name: message.hasDoubleWhitespace
      - name: message.allLinesLessThanThresholdChars
      - name: message.messageIsTypicalNonsense
      - name: message.containsProfanity
