provider:
  name: fileSystemProvider
  path: .
  filters:
    - name: isNotMergeCommit


analyzer:
    rules:
      - name: message.hasSummaryAndDescription
      - name: message.startsWithCapitalLetter
      - name: message.oneBlankLineAfterSummary
      - name: message.summaryFiftyOrLessChars
      - name: message.isTooShort
      - name: message.noTrailingWhitespace
      - name: message.noTrailingNewline
      - name: message.noDoubleWhitespace
      - name: message.allLinesLessThanThresholdChars
      - name: message.notTypicalNonsense
      - name: message.noProfanity
      - name: message.summaryDoesNotEndWithPeriod
      - name: content.hasNoIgnoredFiles
