# This is the main PGCA configuration file

# Settings for the commit provider
provider:

  # Name of the provider
  name: fileSystemProvider

  # Filesystem path of the Git project to analyze
  # Defaults to the current directory
  path: .

  # Limit the number of analyzed commits
  limit: 400

  # Filters to apply to the commit provider
  # A filter is applied to a commit and can exclude the commit from analysis
  filters:
    - name: isNotMergeCommit
    #- name: containsRegex
    #  config:
    #    pattern: /Add/

# Report config
report:

  # The composer to use
  composer: simple

  # The serializer to use
  serializer: console

  # The printer to use
  printer: console

# Tolerance towards violations
# If the violations score is greater than this value, the report command will exit with an error
tolerance: 20

# Commit analyzer config
analyzer:

    # A list of rules to apply during analysis
    rules:
      - name: message.hasSummaryAndDescription
      - name: message.startsWithCapitalLetter
      - name: message.oneBlankLineAfterSummary
      - name: message.summaryFiftyOrLessChars
      - name: message.isLongEnough
        config:
          min: 20
      - name: message.noTrailingWhitespace
      - name: message.noTrailingNewline
      - name: message.noDoubleWhitespace
      - name: message.allLinesLessThanThresholdChars
        config:
          max: 72
      - name: message.notTypicalNonsense
      - name: message.noProfanity
      - name: message.summaryDoesNotEndWithPeriod
      - name: content.hasNoIgnoredFiles
