provider:
  name: fileSystemProvider
  path: ../hubot
  filters:
    - name: isNotMergeCommit
    - name: containsRegex
      config:
        pattern: /typo/i


analyzers:
  message:
    rules:
      - name: message.hasSummaryAndDescription
      - name: message.isTooShort
        config:
          min: 6