provider:
  name: fileSystemProvider
  path: ../hubot
  filters:
    - mergeFilter


analyzers:
  message:
    rules:
      - message.hasSummaryAndDescription
      - message.isReallyShort
      - message.startsWithCapitalLetter