provider:
  name: fileSystemProvider
  path: ../hubot
  filters:
    - name: mergeFilter
    - name: containsRegexFilter
      config:
        pattern: /bower/


analyzers:
  message:
    rules:
      - message.hasSummaryAndDescription
      - message.isReallyShort