provider:
  name: fileSystemProvider
  path: ../hubot
  filters:
    - name: isNotMergeCommit
    - name: containsRegex
      config:
        pattern: /fix/i


analyzers:
  message:
    rules:
      - message.hasSummaryAndDescription
      - message.isReallyShort